name: Build desktop binaries

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Verify script exists
        run: |
          if [ ! -f "photo_resize.py" ]; then
            echo "photo_resize.py not found at repo root"; exit 1;
          fi
        shell: bash

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt pyinstaller

      - name: Build EXE
        run: |
          pyinstaller --noconsole --onefile --name PhotoResize photo_resize.py
        shell: bash

      - name: Upload EXE
        uses: actions/upload-artifact@v4
        with:
          name: PhotoResize-windows
          path: dist/PhotoResize.exe

  build-macos:
    runs-on: macos-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Verify script exists
        run: |
          test -f "photo_resize.py" || (echo "photo_resize.py not found at repo root" && exit 1)

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt pyinstaller

      - name: Build .app
        run: |
          pyinstaller --windowed --name PhotoResize photo_resize.py

      - name: Create DMG
        run: |
          hdiutil create -volname PhotoResize -srcfolder "dist/PhotoResize.app" -ov -format UDZO dist/PhotoResize.dmg

      - name: Upload DMG + .app
        uses: actions/upload-artifact@v4
        with:
          name: PhotoResize-mac
          path: |
            dist/PhotoResize.app
            dist/PhotoResize.dmg
